CREATE TABLE [TRN].[RFPWinzoneOutputFiles] (
    [Id]                           BIGINT         IDENTITY (1, 1) NOT NULL,
    [WinzoneId]                    BIGINT         NOT NULL,
    [BidSummaryDeckPath]           NVARCHAR (300) NULL,
    [RFPSynopsisDocumentPath]      NVARCHAR (300) NULL,
    [NoOfDocuments]                NVARCHAR (500) NULL,
    [ObjectiveSummary]             NVARCHAR (MAX) NULL,
    [AboutSummary]                 NVARCHAR (MAX) NULL,
    [ScopeSummary]                 NVARCHAR (MAX) NULL,
    [BidCalendarDeckPath]          NVARCHAR (500) NULL,
    [DeliverablesSummary]          NVARCHAR (MAX) NULL,
    [SLASummary]                   NVARCHAR (MAX) NULL,
    [ScopeSummaryAPI]              NVARCHAR (MAX) NULL,
    [ObjectiveSummaryAPI]          NVARCHAR (MAX) NULL,
    [DealOnAPagePath]              NVARCHAR (500) NULL,
    [ToolsTechnologiesAPI]         NVARCHAR (MAX) NULL,
    [Timelines]                    NVARCHAR (MAX) NULL,
    [TimelinesAPI]                 NVARCHAR (MAX) NULL,
    [OpenAIDeckPath]               NVARCHAR (500) NULL,
    [SLAAPI]                       NVARCHAR (MAX) NULL,
    [WinThemes]                    NVARCHAR (MAX) NULL,
    [WinThemesAPI]                 NVARCHAR (MAX) NULL,
    [RefreshCount]                 INT            NULL,
    [DeliverablesAPI]              NVARCHAR (MAX) NULL,
    [EvaluationCriteriaAPI]        NVARCHAR (MAX) NULL,
    [ClientLocationAPI]            NVARCHAR (MAX) NULL,
    [SlaKpiAPI]                    NVARCHAR (MAX) NULL,
    [ResponseSubmissionFormatAPI]  NVARCHAR (MAX) NULL,
    [IsAdvanced]                   BIT            NULL,
    [CombinedStatus]               NVARCHAR (100) NULL,
    [ScopeCategoryAPI]             NVARCHAR (MAX) NULL,
    [SuppportCoverageAPI]          NVARCHAR (MAX) NULL,
    [SuppportLanguagesAPI]         NVARCHAR (MAX) NULL,
    [ProductsPlatformsAPI]         NVARCHAR (MAX) NULL,
    [VolumesAPI]                   NVARCHAR (MAX) NULL,
    [OutOfScopeAPI]                NVARCHAR (MAX) NULL,
    [ContractualRequirementsAPI]   NVARCHAR (MAX) NULL,
    [WarrantyRequirementsAPI]      NVARCHAR (MAX) NULL,
    [ReportingRequirementsAPI]     NVARCHAR (MAX) NULL,
    [AutoTransInitiativeAPI]       NVARCHAR (MAX) NULL,
    [ScopeCategoryAPI2]            NVARCHAR (MAX) NULL,
    [CurrentToolsTechnolgyAPI]     NVARCHAR (MAX) NULL,
    [DesiredToolsTechnologyAPI]    NVARCHAR (MAX) NULL,
    [HardwareRequirementsAPI]      NVARCHAR (MAX) NULL,
    [IndustryRegulatoryAPI]        NVARCHAR (MAX) NULL,
    [ClientOverViewForDealOnAPage] NVARCHAR (MAX) NULL,
    [ClientOverViewForBidSummary]  NVARCHAR (MAX) NULL,
    [EBSFlag]                      BIT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

