CREATE TABLE [TRN].[RFPuploadHistory] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [WinzoneID]               BIGINT          NOT NULL,
    [AnalysisStatus]          NVARCHAR (50)   NOT NULL,
    [ProcessID]               BIGINT          NULL,
    [AnalysisStartTime]       DATETIME        NULL,
    [AnalysisEndtime]         DATETIME        NULL,
    [Duration]                BIGINT          NULL,
    [ExceptionComments]       NVARCHAR (MAX)  NULL,
    [UserFeedBack]            NVARCHAR (MAX)  NULL,
    [IsActive]                BIT             NOT NULL,
    [CreatedBy]               BIGINT          NOT NULL,
    [CreatedDate]             DATETIME        NOT NULL,
    [ModifiedBy]              BIGINT          NULL,
    [ModifiedDate]            DATETIME        NULL,
    [BidSummaryDeckPath]      NVARCHAR (3000) NULL,
    [RFPSynopsisDocumentPath] NVARCHAR (300)  NULL,
    [Converted]               INT             NULL,
    [DocumentId]              BIGINT          NULL,
    [DeckExceptionComments]   NVARCHAR (MAX)  NULL,
    [DeckStatus]              NVARCHAR (MAX)  NULL,
    [BidPlanStatus]           NVARCHAR (50)   NULL,
    [DeletedAt]               DATETIME        NULL,
    [BlobFileName]            NVARCHAR (MAX)  NULL,
    [OpenAIDeckStatus]        NVARCHAR (20)   NULL,
    [cost]                    FLOAT (53)      NULL,
    [APIProcessId]            BIGINT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

